version: '3.8'

# Staging environment override
# Usage: docker-compose -f docker-compose.yml -f docker-compose.staging.yml up

services:
  tobelog:
    container_name: tobelog-staging
    ports:
      - "3001:3000"  # Different port for staging
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000
      - DATABASE_URL=sqlite:///home/app/data/blog.db
      - RUST_LOG=info
      - DROPBOX_ACCESS_TOKEN=${DROPBOX_ACCESS_TOKEN}
      - API_KEY=${API_KEY:-staging-api-key}
    volumes:
      # Staging database (separate from production and development)
      - blog_data_staging:/home/app/data
      # Optional: mount staging-specific config
      - ./config:/home/app/config:ro
    networks:
      - tobelog-staging-network
    # Enhanced security for staging (close to production)
    security_opt:
      - no-new-privileges:true
    read_only: true  # Read-only filesystem for security
    user: "1001:1001"
    cap_drop:
      - ALL
    # Staging-specific health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # Resource limits for staging
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

networks:
  tobelog-staging-network:
    driver: bridge
    name: tobelog-staging-network

volumes:
  blog_data_staging:
    driver: local
    name: tobelog-blog-data-staging